default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: <%=ENV['IP']%>
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: < %=ENV['PRO_APPNAME']%>
  host: < %=ENV['$PRO_POSTGRESQL_DB_HOST']%>
  port: < %=ENV['$PRO_POSTGRESQL_DB_PORT']%>
  username: < %=ENV['PRO_POSTGRESQL_DB_USERNAME']%>
  password: < %=ENV['PRO_POSTGRESQL_DB_PASSWORD']%>